-- softcut experiments

local sc = {}

function sc.init()
  print("starting softcut/tunnels")
  
	audio.level_cut(1.0)
	audio.level_adc_cut(1)
	audio.level_eng_cut(1)
  softcut.level(1,1.0)
  softcut.level(2,1.0)
  softcut.level(3,1.0)
  softcut.level(4,1.0)
  softcut.level(5,0.0)
  softcut.level(6,0.0)
	softcut.level_input_cut(1, 1, 1.0)
	softcut.level_input_cut(1, 2, 0.0)
	softcut.level_input_cut(2, 1, 1.0)
	softcut.level_input_cut(2, 2, 0.0)
	softcut.level_input_cut(3, 1, 1.0)
	softcut.level_input_cut(3, 2, 0.0)
	softcut.level_input_cut(4, 1, 1.0)
	softcut.level_input_cut(4, 2, 0.0)
	softcut.level_input_cut(5, 1, 0.0)
	softcut.level_input_cut(6, 1, 0.0)
	softcut.level_cut_cut(1, 2, 0.2)
	softcut.level_cut_cut(3, 4, 0.2)
	softcut.level_cut_cut(4, 2, 0.15)
	softcut.level_cut_cut(3, 1, 0.15)
	--softcut.level_cut_cut(1, 3, 0.2)
	--softcut.level_cut_cut(2, 4, 0.2)
	--softcut.level_cut_cut(4, 1, 0.2)
	--softcut.level_cut_cut(3, 2, 0.2)
	softcut.pan(1, 0.75)
	softcut.pan(2, 0.25)
	softcut.pan(3, 0.60)
	softcut.pan(4, 0.40)
	softcut.pan(5, 0.3)
	softcut.pan(6, 0.7)

  softcut.buffer(1, 1)
  softcut.play(1, 1)
	softcut.rate(1, 1)
	softcut.loop_start(1, 0)
	softcut.loop_end(1, 5)
	softcut.loop(1, 1)
	softcut.fade_time(1, 0.2)
	softcut.rec(1, 1)
	softcut.rec_level(1, 1)
	softcut.pre_level(1, 0.70)
	softcut.position(1, 0)
	softcut.enable(1, 1)
	
	softcut.buffer(2, 2)
	softcut.play(2, 1)
	softcut.rate(2, 1)
	softcut.loop_start(2, 0)
	softcut.loop_end(2, 4)
	softcut.loop(2, 1)
	softcut.fade_time(2, 0.2)
	softcut.rec(2, 1)
	softcut.rec_level(2, 1)
	softcut.pre_level(2, 0.65)
	softcut.position(2, 0)
	softcut.enable(2, 1)
	
	softcut.buffer(3, 2)
	softcut.play(3, 1)
	softcut.rate(3, 2)
	softcut.loop_start(3, 0)
	softcut.loop_end(3, 3)
	softcut.loop(3, 1)
	softcut.fade_time(3, 0.2)
	softcut.rec(3, 1)
	softcut.rec_level(3, 1)
	softcut.pre_level(3, 0.85)
	softcut.position(3, 0.5)
	softcut.enable(3, 1)
	
	softcut.buffer(4, 1)
	softcut.play(4, 1)
	softcut.rate(4, -4)
	softcut.loop_start(4, 0)
	softcut.loop_end(4, 2)
	softcut.loop(4, 1)
	softcut.fade_time(4, 0.2)
	softcut.rec(4, 1)
	softcut.rec_level(4, 1)
	softcut.pre_level(4, 0.85)
	softcut.position(4, 0)
	softcut.enable(4, 1)
	
	for i=1,4 do 
    softcut.filter_dry(i, 0.125);
	  softcut.filter_fc(i, 1200);
	  softcut.filter_lp(i, 0);
	  softcut.filter_bp(i, 1.0);
	  softcut.filter_rq(i, 2.0);
  end
	
	softcut.buffer(5, 1)
	softcut.play(5, 1)
	softcut.rate(5, 1)
	softcut.loop_start(5, 0)
	softcut.loop_end(5, 2)
	softcut.loop(5, 1)
	softcut.fade_time(5, 0.4)
	softcut.rec(5, 0)
	softcut.rec_level(5, 1)
	softcut.pre_level(5, 0.1)
	softcut.position(5, 0)
	softcut.enable(5, 1)
	softcut.filter_bp(5, 0.6);
	
	softcut.buffer(6, 1)
	softcut.play(6, 1)
	softcut.rate(6, 1)
	softcut.loop_start(6, 0)
	softcut.loop_end(6, 2)
	softcut.loop(6, 1)
	softcut.fade_time(6, 0.4)
	softcut.rec(6, 0)
	softcut.rec_level(6, 1)
	softcut.pre_level(6, 0.1)
	softcut.position(6, 0)
	softcut.enable(6, 1)
	softcut.filter_bp(6, 0.4);

  --params:add_separator()
  local p = softcut.params()
  params:add(p[1].rate)
  params:add(p[2].rate)
  params:add(p[3].rate)
  params:add(p[4].rate)
  params:add(p[1].fade_time)
  params:add(p[2].fade_time)
  params:add(p[3].fade_time)
  params:add(p[4].fade_time)
  params:add(p[1].pre_level)
  params:add(p[2].pre_level)
  params:add(p[3].pre_level)
  params:add(p[4].pre_level)
  params:add(p[1].filter_lp)
  params:add(p[2].filter_lp)
  params:add(p[3].filter_lp)
  params:add(p[4].filter_lp)
end

return sc
